# Generated by Django 4.0.6 on 2022-07-31 16:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=175, null=True)),
                ('slug', models.CharField(max_length=120, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
                'db_table': 'Foodie_category',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=120, null=True)),
                ('slug', models.CharField(max_length=120, null=True)),
                ('url', models.URLField(max_length=175)),
                ('enabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'City',
                'db_table': 'Foodie_city',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=120, null=True)),
                ('state', models.CharField(max_length=120, null=True)),
                ('slug', models.CharField(max_length=120, null=True)),
                ('edabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Location',
                'db_table': 'Foodie_location',
            },
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('resturant_id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('resturant', models.CharField(blank=True, max_length=175, null=True)),
                ('resturant_type', models.CharField(blank=True, max_length=175, null=True)),
                ('address_locality', models.CharField(blank=True, max_length=220, null=True)),
                ('address_region', models.CharField(blank=True, max_length=220, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=125, null=True)),
                ('address_country', models.CharField(blank=True, max_length=220, null=True)),
                ('street_address', models.CharField(blank=True, max_length=220, null=True)),
                ('phone', models.CharField(blank=True, max_length=220, null=True)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('review_count', models.CharField(blank=True, max_length=220, null=True)),
                ('opening_hours', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.city')),
            ],
            options={
                'verbose_name_plural': 'Restaurant',
                'db_table': 'Foodie_restaurant',
            },
        ),
        migrations.CreateModel(
            name='ResturantCategory',
            fields=[
                ('resturant_category_id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.category')),
                ('resturant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.resturant')),
            ],
            options={
                'verbose_name_plural': 'RestaurantCategory',
                'db_table': 'Foodie_restaurant_category',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('menu', models.CharField(max_length=220, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField(default=0.0, max_length=155, null=True)),
                ('currency', models.CharField(default='INR', max_length=5, null=True)),
                ('status', models.BooleanField(default=True)),
                ('resturant_url', models.URLField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('resturant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.resturant')),
            ],
            options={
                'verbose_name_plural': 'Menu',
                'db_table': 'Foodie_menu',
            },
        ),
        migrations.CreateModel(
            name='CityCategory',
            fields=[
                ('city_category_id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.city')),
            ],
            options={
                'verbose_name_plural': 'CityCategory',
                'db_table': 'Foodie_city_category',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.location'),
        ),
        migrations.AddIndex(
            model_name='resturant',
            index=models.Index(fields=['url'], name='Foodie_rest_url_43657b_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['url'], name='Foodie_city_url_a58cc5_idx'),
        ),
    ]
